rm *.csv

python dic_batch_process.py bee 01
python dic_batch_process.py bee 02
python dic_batch_process.py bee 03
python dic_batch_process.py bee 04
python dic_batch_process.py bee 05
python dic_batch_process.py bee 06
python dic_batch_process.py bee 07
python dic_batch_process.py bee 08
python dic_batch_process.py bee 09
python dic_batch_process.py bee 10
python dic_batch_process.py bee 11
python dic_batch_process.py bee 12
python dic_batch_process.py bee 13
python dic_batch_process.py bee 14
python dic_batch_process.py bee 15

python dic_batch_process.py beetle 01
python dic_batch_process.py beetle 02
python dic_batch_process.py beetle 03
python dic_batch_process.py beetle 04
python dic_batch_process.py beetle 05
python dic_batch_process.py beetle 06
python dic_batch_process.py beetle 07
python dic_batch_process.py beetle 08
python dic_batch_process.py beetle 09
python dic_batch_process.py beetle 10
python dic_batch_process.py beetle 11
python dic_batch_process.py beetle 12
python dic_batch_process.py beetle 13
python dic_batch_process.py beetle 14
python dic_batch_process.py beetle 15

python dic_batch_process.py butterfly 01
python dic_batch_process.py butterfly 02
python dic_batch_process.py butterfly 03
python dic_batch_process.py butterfly 04
python dic_batch_process.py butterfly 05
python dic_batch_process.py butterfly 06
python dic_batch_process.py butterfly 07
python dic_batch_process.py butterfly 08
python dic_batch_process.py butterfly 09
python dic_batch_process.py butterfly 10
python dic_batch_process.py butterfly 11
python dic_batch_process.py butterfly 12
python dic_batch_process.py butterfly 13
python dic_batch_process.py butterfly 14
python dic_batch_process.py butterfly 15

python dic_batch_process.py cicada 01
python dic_batch_process.py cicada 02
python dic_batch_process.py cicada 03
python dic_batch_process.py cicada 04
python dic_batch_process.py cicada 05
python dic_batch_process.py cicada 06
python dic_batch_process.py cicada 07
python dic_batch_process.py cicada 08
python dic_batch_process.py cicada 09
python dic_batch_process.py cicada 10
python dic_batch_process.py cicada 11
python dic_batch_process.py cicada 12
python dic_batch_process.py cicada 13
python dic_batch_process.py cicada 14
python dic_batch_process.py cicada 15

python dic_batch_process.py cockroach 01
python dic_batch_process.py cockroach 02
python dic_batch_process.py cockroach 03
python dic_batch_process.py cockroach 04
python dic_batch_process.py cockroach 05
python dic_batch_process.py cockroach 06
python dic_batch_process.py cockroach 07
python dic_batch_process.py cockroach 08
python dic_batch_process.py cockroach 09
python dic_batch_process.py cockroach 10
python dic_batch_process.py cockroach 11
python dic_batch_process.py cockroach 12
python dic_batch_process.py cockroach 13
python dic_batch_process.py cockroach 14
python dic_batch_process.py cockroach 15

python dic_batch_process.py dragonfly 01
python dic_batch_process.py dragonfly 02
python dic_batch_process.py dragonfly 03
python dic_batch_process.py dragonfly 04
python dic_batch_process.py dragonfly 05
python dic_batch_process.py dragonfly 06
python dic_batch_process.py dragonfly 07
python dic_batch_process.py dragonfly 08
python dic_batch_process.py dragonfly 09
python dic_batch_process.py dragonfly 10
python dic_batch_process.py dragonfly 11
python dic_batch_process.py dragonfly 12
python dic_batch_process.py dragonfly 13
python dic_batch_process.py dragonfly 14
python dic_batch_process.py dragonfly 15

python dic_batch_process.py fly 01
python dic_batch_process.py fly 02
python dic_batch_process.py fly 03
python dic_batch_process.py fly 04
python dic_batch_process.py fly 05
python dic_batch_process.py fly 06
python dic_batch_process.py fly 07
python dic_batch_process.py fly 08
python dic_batch_process.py fly 09
python dic_batch_process.py fly 10
python dic_batch_process.py fly 11
python dic_batch_process.py fly 12
python dic_batch_process.py fly 13
python dic_batch_process.py fly 14
python dic_batch_process.py fly 15

python dic_batch_process.py grasshopper 01
python dic_batch_process.py grasshopper 02
python dic_batch_process.py grasshopper 03
python dic_batch_process.py grasshopper 04
python dic_batch_process.py grasshopper 05
python dic_batch_process.py grasshopper 06
python dic_batch_process.py grasshopper 07
python dic_batch_process.py grasshopper 08
python dic_batch_process.py grasshopper 09
python dic_batch_process.py grasshopper 10
python dic_batch_process.py grasshopper 11
python dic_batch_process.py grasshopper 12
python dic_batch_process.py grasshopper 13
python dic_batch_process.py grasshopper 14
python dic_batch_process.py grasshopper 15

python dic_batch_process.py mantis 01
python dic_batch_process.py mantis 02
python dic_batch_process.py mantis 03
python dic_batch_process.py mantis 04
python dic_batch_process.py mantis 05
python dic_batch_process.py mantis 06
python dic_batch_process.py mantis 07
python dic_batch_process.py mantis 08
python dic_batch_process.py mantis 09
python dic_batch_process.py mantis 10
python dic_batch_process.py mantis 11
python dic_batch_process.py mantis 12
python dic_batch_process.py mantis 13
python dic_batch_process.py mantis 14
python dic_batch_process.py mantis 15

python dic_batch_process.py wasp 01
python dic_batch_process.py wasp 02
python dic_batch_process.py wasp 03
python dic_batch_process.py wasp 04
python dic_batch_process.py wasp 05
python dic_batch_process.py wasp 06
python dic_batch_process.py wasp 07
python dic_batch_process.py wasp 08
python dic_batch_process.py wasp 09
python dic_batch_process.py wasp 10
python dic_batch_process.py wasp 11
python dic_batch_process.py wasp 12
python dic_batch_process.py wasp 13
python dic_batch_process.py wasp 14
python dic_batch_process.py wasp 15
